### ISSUE TITLE
Add new mountain 

### ISSUE THREAD

**Issue by OkiRules** [pirxpilot/liftie#18]
Please add Mount Buller as one of the mountains

**Comment by pirxpilot** [comment]
This is how you can do it: https://github.com/pirxpilot/liftie#how-to-add-your-favorite--acmecom-resort
Get it started and I'll help with PR

**Comment by OkiRules** [comment]
I have already looked at that and generated a mt buller but when I try to run the function: make this is what happens:

151 passing (2s)
  4 pending
  1 failing

  1) parse mt-buller
       should return lift status:

      Uncaught AssertionError: expected Object {} to equal Object { 'lift 1': 'open' }
      + expected - actual

      -{}
      +{
      +  "lift 1": "open"
      +}
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at test/resorts/mt-buller.js:17:21
      at IgnoreEmptiesDomHandler.handle [as _callback] (lib/lifts/parser.js:68:5)
      at IgnoreEmptiesDomHandler.DomHandler._handleCallback.DomHandler.onerror (node_modules/domhandler/index.js:52:8)
      at IgnoreEmptiesDomHandler.DomHandler.onend (node_modules/domhandler/index.js:46:7)
      at Parser.onend (node_modules/htmlparser2/lib/Parser.js:310:32)
      at Tokenizer._finish (node_modules/htmlparser2/lib/Tokenizer.js:838:12)
      at Tokenizer.end (node_modules/htmlparser2/lib/Tokenizer.js:829:25)
      at Parser.end (node_modules/htmlparser2/lib/Parser.js:338:18)
      at Stream.<anonymous> (node_modules/htmlparser2/lib/WritableStream.js:15:10)
      at finishMaybe (_stream_writable.js:604:14)
      at endWritable (_stream_writable.js:612:3)
      at Stream.Writable.end (_stream_writable.js:563:5)
      at ReadStream.onend (_stream_readable.js:595:10)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)



make: *** [test] Error 1

**Comment by pirxpilot** [comment]
Nice. That's a good start. Push your branch to github and I'll have a look.

**Comment by pirxpilot** [comment]
There are quite a few docs out there. See if any of those might help:
https://gist.github.com/Chaser324/ce0505fbed06b947d962
https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/

**Comment by OkiRules** [comment]
Sorry ive had a look at both articles and still cant seem to work out how to push.

Could you please add Mt. Buller for me?

**Comment by OkiRules** [comment]
Any update on adding Mount Buller?

**Comment by OkiRules** [comment]
Hello?

**Comment by OkiRules** [comment]
Please respond?!

**Comment by OkiRules** [comment]
Please have a look at the mt buller test that I have created as a pull request.

**Comment by OkiRules** [comment]
any update? I have created a pull request :)

**Comment by OkiRules** [comment]
Hi,

Trying to parse the mt-buller JSON I get this error, the error has nothing to do with the code I am using but a JSON server side issue as all the other resorts parse correctly...

Error is as follows: "JSON text did not start with array or object and option to allow fragments not set."

Thanks in advance

**Comment by pirxpilot** [comment]
Not entirely sure what you mean by that. Are you using liftie REST API? If so that seem to work OK. [jq] does not seem to have any problems with what liftie returns.

    curl https://liftie.info/api/resort/mt-buller | jq

[jq]: https://stedolan.github.io/jq/

**Comment by OkiRules** [comment]
When using JSONDecoder().decode in swift that error seems to pop up...
