### ISSUE TITLE
Another ERROR...

### ISSUE THREAD

**Issue by OkiRules** [pirxpilot/liftie#20]
This error is created while trying to run: node app:

```
module.js:540
    throw err;
    ^

Error: Cannot find module './resorts/.DS_Store/resort.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /Users/oscargorog/liftie/lib/loader.js:11:20
    at Array.reduce (<anonymous>)
    at /Users/oscargorog/liftie/lib/loader.js:10:22
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by pirxpilot** [comment]
Looks like the result of running into #19 (which is fixed on master now). Removing the empty directory created by generate:

    rm -rf lib/resorts/mt-baw-baw/ 

or re-running the `generate` script should take care of that.
