### ISSUE TITLE
Makefile fails on win10

### ISSUE THREAD

**Issue by VladyaRazumist** [pirxpilot/liftie#33]
After running "yarn" executing "make" under Cygwin64 terminal fails with such errors : 

_TypeError: Cannot read property 'slice' of null
    at parseHeaders (G:\liftie\node_modules\@pirxpilot\replay\src\catalog.js:32:55)
    at parseRequest (G:\liftie\node_modules\@pirxpilot\replay\src\catalog.js:69:19)
    at Catalog._read (G:\liftie\node_modules\@pirxpilot\replay\src\catalog.js:256:17)
    at Catalog.find (G:\liftie\node_modules\@pirxpilot\replay\src\catalog.js:195:28)
    at G:\liftie\node_modules\@pirxpilot\replay\src\recorder.js:15:32
    at Function.layer [as next] (G:\liftie\node_modules\@pirxpilot\replay\src\chain.js:50:7)
    at G:\liftie\node_modules\@pirxpilot\replay\src\chain.js:54:17
    at G:\liftie\node_modules\@pirxpilot\replay\src\logger.js:16:5
    at Function.layer [as next] (G:\liftie\node_modules\@pirxpilot\replay\src\chain.js:50:7)
    at G:\liftie\node_modules\@pirxpilot\replay\src\chain.js:54:17
Emitted 'error' event on PassThrough instance at:
    at ProxyRequest.propagateError (G:\liftie\node_modules\getlet\lib\getlet.js:147:10)
    at ProxyRequest.emit (events.js:322:22)
    at Immediate.<anonymous> (G:\liftie\node_modules\@pirxpilot\replay\src\proxy.js:121:16)
    at processImmediate (internal/timers.js:456:21) {
  code: 'CORRUPT FIXTURE',
  syscall: 'connect'

  10 tests
  15 passed

  Pass!
NODE_PATH=lib/client:node_modules \
./node_modules/.bin/browserify \
--require resort/lifts \
--require resort/twitter \
--require resort/weather \
--require resort/webcams \
--require resort/snow \
--entry lib/client/boot/index.js \
--outfile public/scripts/liftie.js
Error: Cannot find module 'resort/lifts' from 'G:\liftie'
    at G:\liftie\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (G:\liftie\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (G:\liftie\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (G:\liftie\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (G:\liftie\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at G:\liftie\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:167:21)
make: *** [Makefile:48: public/scripts/liftie.js]_

Could you help and tell what am i doing wrong? Maybe there is a better way to make it work under windows.

**Comment by pirxpilot** [comment]
Sorry - I don't have a Windows machine. Not sure what's wrong here. It seems similar to this [replay issue][1] on Windows but I can't see any explanation or fix for it.

Check what version of node are you have installed (run `node --version`) - I am using 12.16.1 but any >= 12 should be OK.

And if nothing else helps maybe you can look into running [Ubuntu on Windows][2] instead of CygWin.

[1]: https://github.com/assaf/node-replay/issues/146
[2]: https://ubuntu.com/tutorials/tutorial-ubuntu-on-windows#1-overview
